steps:
  - id: terraform-init
    name: hashicorp/terraform:0.12.24
    args: ["init", "-backend-config=bucket=prd-gcs-tfstate"]
    dir: "terraform"
    env:
      - "TF_VAR_gcp_project=$PROJECT_ID"

  - id: terraform-plan
    name: hashicorp/terraform:0.12.24
    args: ["plan", "-var-file=prd.tfvars"]
    dir: "terraform"
    env:
      - "TF_VAR_gcp_project=$PROJECT_ID"
