---
- name: wordpressのダウンロード
  get_url:
    url: https://ja.wordpress.org/wordpress-5.6.2-ja.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: wordpressの展開
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/ copy=no

- name: wordpressの所有権をapacheに変更
  file:
    path: /var/www/html/wordpress/
    owner: apache
    group: apache
    recurse: yes

- name: httpサービスの再起動
  systemd:
    name: httpd
    state: restarted
    enabled: yes
